=== KatoAndras/S7KTW0XML/S7KTW0_0924/S7KTW0_kurzusfelvetel.dtd
<?xml version="1.0" encoding="UTF-8"?>

	<!ELEMENT S7KTW0_kurzusfelvetel (hallgatok, kurzusok)>
	<!ATTLIST S7KTW0_kurzusfelvetel tanÃ©v CDATA #REQUIRED>
	<!ATTLIST S7KTW0_kurzusfelvetel egyetem CDATA #REQUIRED>
	    
	<!ELEMENT hallgatok (hallgato)>
	
	<!ELEMENT hallgato (hnev, szulev, szak)>
	<!ELEMENT hnev (#PCDATA)>
	<!ELEMENT szulev (#PCDATA)>
	<!ELEMENT szak (#PCDATA)>
	<!ATTLIST szak evf CDATA #REQUIRED>
	
	<!ELEMENT kurzusok (kurzus*)>
	
	<!ELEMENT kurzus (kurzusnev, kredit, hely, idopont+, oktato?, oraado?)>
	<!ATTLIST kurzus id CDATA #REQUIRED>
	<!ATTLIST kurzus jovahagyas (igen | nem) "nem">
	<!ATTLIST kurzus nyelv CDATA #IMPLIED>
	<!ELEMENT kurzusnev (#PCDATA)>
	<!ELEMENT kredit (#PCDATA)>
	<!ELEMENT hely (#PCDATA)>
	<!ELEMENT idopont (#PCDATA)>
	<!ELEMENT oktato (#PCDATA)>
	<!ELEMENT oraado (#PCDATA)>

=== KatoAndras/S7KTW0XML/S7KTW0_1015/S7KTW0_kurzusfelvetel.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE S7KTW0_kurzusfelvetel SYSTEM "S7KTW0_kurzusfelvetel.dtd">

<S7KTW0_kurzusfelvetel tanév="2024/25_1_felev" egyetem="Miskolci Egyetem">

	<hallgatok>
		
		<hallgato>
	        <hnev>Kató András</hnev>
	        <szulev>2000</szulev>
	        <szak evf="2019/20">Programtervező Informatikus</szak>
   		 </hallgato>
   		 
	</hallgatok>
    
    <kurzusok>
		
        <kurzus id="S7KTW0" jovahagyas="igen" nyelv="magyar">
            <kurzusnev>Adatkezelés XML-ben</kurzusnev>
            <kredit>5</kredit>
            <hely>In/103</hely>
            <idopont>Kedd 10:00</idopont>
            <oktato>Dr. Bednarik László</oktato>
	    <oraado>Kovács Mercédesz</oraado>
        </kurzus>
        
        <kurzus id="WRMF12" jovahagyas="igen" nyelv="magyar">
            <kurzusnev>Web Technológiák 1.</kurzusnev>
            <kredit>5</kredit>
            <hely>A3</hely>
            <idopont>Szerda 16:00</idopont>
            <oktato>Nyitrai Emese</oktato>
            <oraado>Halász Kinga</oraado>
        </kurzus>
        
        <kurzus id="FH25DE">
            <kurzusnev>Szotvertechnológia</kurzusnev>
            <kredit>5</kredit>
            <hely>A4</hely>
            <idopont>Szerda 08:00</idopont>
            <oktato>Dr. Mileff Péter</oktato>
        </kurzus>
        
        <kurzus id="KJIO78">
            <kurzusnev>Angol Szaknyelvi Szövegértés</kurzusnev>
            <kredit>2</kredit>
            <hely>A220</hely>
            <idopont>Kedd 12:00</idopont>
            <oktato>Ajtonyi Angéla</oktato>
        </kurzus>
        
    </kurzusok>
    
</S7KTW0_kurzusfelvetel>
