<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE KA_orarend [

	<!ELEMENT KA_orarend (ora+)>

	<!ELEMENT ora (targy, idopont, helyszin, oktato, szak)>
	
	<!ATTLIST ora id ID #REQUIRED>
	<!ATTLIST ora tipus (előadás | gyakorlat) "előadás">
	
	<!ELEMENT targy (#PCDATA)>
	<!ELEMENT idopont (nap, tol, ig)>
		<!ELEMENT nap (#PCDATA)>
		<!ELEMENT tol (#PCDATA)>
		<!ELEMENT ig (#PCDATA)>
	<!ELEMENT helyszin (#PCDATA)>
	<!ELEMENT oktato (#PCDATA)>
	<!ELEMENT szak (#PCDATA)>
]>

<KA_orarend>

		<ora id="ora_1" tipus="előadás">
			<targy> Adatkezelés XML-ben </targy>
			<idopont>
				<nap> kedd </nap>
				<tol> 10 </tol>
				<ig> 12 </ig>
			</idopont>
			<helyszin> Inf/103 </helyszin>
			<oktato> Dr. Bednarik László </oktato>
			<szak> Programtervező Informatikus </szak>
		</ora>
		<ora id="ora_2" tipus="gyakorlat">
			<targy> Adatkezelés XML-ben </targy>
			<idopont>
				<nap> kedd </nap>
				<tol> 12 </tol>
				<ig> 14 </ig>
			</idopont>
			<helyszin> Inf/103 </helyszin>
			<oktato> Dr. Bednarik László </oktato>
			<szak> Programtervező Informatikus </szak>
		</ora>

		<ora id="ora_3" tipus="előadás">
			<targy> Szoftvertechnológia </targy>
			<idopont>
				<nap> szerda </nap>
				<tol> 08 </tol>
				<ig> 10 </ig>
			</idopont>
			<helyszin> III. Előadó </helyszin>
			<oktato> Dr. Mileff Péter </oktato>
			<szak> Programtervező Informatikus </szak>
		</ora>
		<ora id="ora_4" tipus="gyakorlat">
			<targy> Szoftvertechnológia </targy>
			<idopont>
				<nap> szerda </nap>
				<tol> 08 </tol>
				<ig> 10 </ig>
			</idopont>
			<helyszin> III. Előadó </helyszin>
			<oktato> Dr. Mileff Péter </oktato>
			<szak> Programtervező Informatikus </szak>
		</ora>

</KA_orarend>